trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: terraform-secrets

stages:
  - stage: Security_Scan
    displayName: "Stage 1 - Security Scan"
    jobs:
      - job: Checkov
        displayName: "Checkov + Gitleaks"
        steps:
          - script: |
              pip install checkov --break-system-packages
              checkov -d . --quiet
            displayName: "Checkov IaC Scan"
            workingDirectory: $(System.DefaultWorkingDirectory)

          - script: |
              wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
              tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
              ./gitleaks detect --source . --verbose
            displayName: "Gitleaks Secret Scan"

  - stage: Plan
    displayName: "Terraform Plan"
    jobs:
      - job: TerraformPlan
        steps:

          - script: |
              wget -O terraform.zip https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/
              terraform --version
            displayName: "Install Terraform"

          - script: |
              cd environments/dev
              terraform init \
                -backend-config="access_key=$(TF_STORAGE_KEY)"
            displayName: "Terraform Init"
            env:
              ARM_CLIENT_ID:       $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:   $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID:       $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

          - script: |
              cd environments/dev
              terraform plan -var-file="terraform.tfvars"
            displayName: "Terraform Plan"
            env:
              ARM_CLIENT_ID:       $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:   $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID:       $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

  - stage: Approve
    displayName: "Stage 3 - Approval Gate"
    dependsOn: Plan
    jobs:
      - deployment: WaitForApproval
        displayName: "Manual Approval"
        environment: "dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Approved — proceeding to apply"
                  displayName: "Approval confirmed"


  - stage: Apply
    displayName: "Stage 4 - Terraform Apply"
    dependsOn: Approve
    jobs:
      - job: TerraformApply
        displayName: "Terraform Apply"
        steps:
          - script: |
              wget -O terraform.zip https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/
            displayName: "Install Terraform"

          - script: |
              cd environments/dev
              terraform init \
                -backend-config="access_key=$(TF_STORAGE_KEY)"
              terraform apply -var-file="terraform.tfvars" -auto-approve
            displayName: "Terraform Apply"
            env:
              ARM_CLIENT_ID:       $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:   $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID:       $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)